In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# The catch here is that numpy makes array operations element-wise
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print(a+b)
print(f"shape {a.shape}")
print(f"size {a.size}")

[2 4 6]
shape (3,)
size 3


In [3]:
e = np.array([ [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
# no me queda claro si el reshape es un unravel total, si quita la innermost o la outermost dimensión
print(f"shape {e.shape}")
# e = e.reshape(-1)
# print(e)
# convertir ahora sí a un tensor mi bro
e = tf.convert_to_tensor(e)
c = e
print(c+e)
print(c/e)

shape (2, 3, 3)
tf.Tensor(
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]], shape=(2, 3, 3), dtype=int64)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float64)


In [4]:
# vamos a probar la diferencia entre tensorflow tensors y numpy arrays (parallel vs element-wise)
import time

In [5]:
a = np.arange(1000000, dtype=np.float32)
b = np.arange(1000000, dtype=np.float32)
start = time.perf_counter_ns()
c = a + b
end = time.perf_counter_ns()
time_elapsed = end-start
print(f"time elapsed for numpy: {time_elapsed}")

a = tf.convert_to_tensor(a)
b = tf.convert_to_tensor(b)
start = time.perf_counter_ns()
c = a + b
end = time.perf_counter_ns()
time_elapsed = end-start
print(f"time elapsed for numpy: {time_elapsed}")
# turns out for simple operations numpy might occasionally win cause it is highly optimized

time elapsed for numpy: 3165600
time elapsed for numpy: 6643900
